services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user-service'
      - 'POSTGRES_PASSWORD=7482040607'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5441:5432'
