server:
  port: 9091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5441/user-service
    username: postgres
    password: 7482040607
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true